modLoader="javafml" #mandatory
loaderVersion="[44,)" #mandatory
license="All rights reserved"

[[mods]] #mandatory
modId="phenomena" #mandatory
logoFile="PhenomenaLogo.png"
version="${mod_version}" #mandatory
displayName="Phenomena Structures" #mandatory
credits="Thanks for this mod goes to Java!"
authors="Mckeksik(MckeksikYTB) and Davidak(davidgmc18)" #optional
description='''
Adding various structures to your world. Including Nether and End!!!
'''

# makes sure our mod does not be attempted to be ran on older version of Minecraft and explodes
[[dependencies.phenomena]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20, 1.21)"
    side="SERVER"