modLoader="javafml" #mandatory
loaderVersion="[43,)" #mandatory
license="All rights reserved"

[[mods]] #mandatory
modId="phenomena" #mandatory
logoFile="PhenomenaLogo.png"
version="${mod_version}" #mandatory
displayName="Phenomena Structures" #mandatory
credits="Thanks for this mod goes to Java!"
authors="Mckeksik(MckeksikYTB) and Davidak(davidgmc18)" #optional
description='''
Adding various structures to your world. Including Nether and End!!!
'''

[[dependencies.phenomena]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2, 1.20)"
    side="SERVER"
